# syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1785825911@sha256:cb964eb2bf491814a681bc9887c83d32d6d4eac7b491c5c8c7fe641a5c586a09

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY mc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

RUN microdnf update --nodocs --assumeyes && \
    microdnf install ca-certificates --nodocs --assumeyes && \
    microdnf clean all

ENTRYPOINT ["mc"]
