# syntax=docker/dockerfile:1@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10-1785825911@sha256:cb964eb2bf491814a681bc9887c83d32d6d4eac7b491c5c8c7fe641a5c586a09

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY mc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

RUN microdnf update --nodocs --assumeyes && \
    microdnf install ca-certificates --nodocs --assumeyes && \
    microdnf clean all

ENTRYPOINT ["mc"]
